package org.gmod.schema.mapped;

// Generated Aug 31, 2006 4:02:18 PM by Hibernate Tools 3.2.0.beta7

import static javax.persistence.GenerationType.SEQUENCE; //added explicit sequence generation behaviour 2.12.2015

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.GeneratedValue;
import javax.persistence.SequenceGenerator;


/**
 * PhylonodeDbXRef generated by hbm2java
 */
@Entity
@Table(name = "phylonode_dbxref", uniqueConstraints = { @UniqueConstraint(columnNames = {
        "phylonode_id", "dbxref_id" }) })
public class PhylonodeDbXRef implements java.io.Serializable {

    // Fields
	@SequenceGenerator(name = "generator", sequenceName = "phylonode_dbxref_phylonode_dbxref_id_seq",  allocationSize=1)
    @Id @GeneratedValue(strategy = SEQUENCE, generator = "generator")
    @Column(name = "phylonode_dbxref_id", unique = true, nullable = false, insertable = true, updatable = true)
    private int phylonodeDbXRefId;

    @ManyToOne(cascade = {}, fetch = FetchType.LAZY)
    @JoinColumn(name = "dbxref_id", unique = false, nullable = false, insertable = true, updatable = true)
    private DbXRef dbXRef;

    @ManyToOne(cascade = {}, fetch = FetchType.LAZY)
    @JoinColumn(name = "phylonode_id", unique = false, nullable = false, insertable = true, updatable = true)
    private Phylonode phylonode;

    // Constructors

    PhylonodeDbXRef() {
        // Deliberately empty default constructor
    }

    /** full constructor */
    public PhylonodeDbXRef(DbXRef dbXRef, Phylonode phylonode) {
        this.dbXRef = dbXRef;
        this.phylonode = phylonode;
    }

    // Property accessors
    public int getPhylonodeDbXRefId() {
        return this.phylonodeDbXRefId;
    }

    public DbXRef getDbXRef() {
        return this.dbXRef;
    }

    void setDbXRef(DbXRef dbXRef) {
        this.dbXRef = dbXRef;
    }

    public Phylonode getPhylonode() {
        return this.phylonode;
    }

    void setPhylonode(Phylonode phylonode) {
        this.phylonode = phylonode;
    }

}
